### ISSUE TITLE
PSR-15 support?

### ISSUE THREAD

**Issue by MassiAtZend** [mvlabs/ze-content-validation#7]
Hi guys, I love this project, but as I am sure you know, it is not PSR-15 compatible.

Do you plan to update it for PSR-15?
Do you have another project that does so?

Thanks and regards,
Massi.

**Comment by drigani** [comment]
@MassiAtZend Yes, I have planned to release a new version that will upgrade to PSR-15 in the near future. 
If you are interested in contributing, PR are welcomed!

**Comment by drigani** [comment]
Hi @MassiAtZend, we just released a new PSR-15 compatible version: [2.0.0](https://github.com/mvlabs/ze-content-validation/tree/2.0.0)
Feedback is welcome!
Thanks and regards,
Diego
